#!/bin/sh
#
# PROVIDE: mdns_ws
# REQUIRE: mdnsd DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="mdns_ws"
rcvar="mdns_ws_enable"
pidfile="/var/run/mdns_ws.pid"
command="/usr/sbin/daemon"
command_args="-p ${pidfile} -f /home/matuzalem/bin/mdns_hostname.sh"

load_rc_config $name
: ${mdns_ws_enable:=no}

mdns_ws_stop() {
    if [ -f "${pidfile}" ]; then
        kill `cat ${pidfile}` 2>/dev/null
        # Give the process time to exit
        sleep 1
        rm -f ${pidfile}
    fi
}

mdns_ws_status() {
    if [ -f "${pidfile}" ] && kill -0 `cat ${pidfile}` 2>/dev/null; then
        echo "mdns_ws is running (pid `cat ${pidfile}`)"
        return 0
    else
        echo "mdns_ws is not running"
        return 1
    fi
}

stop_cmd="mdns_ws_stop"
status_cmd="mdns_ws_status"

run_rc_command "$1"
