#!/bin/sh
#
# PROVIDE: mdns_afp
# REQUIRE: mdnsd DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="mdns_afp"
rcvar="mdns_afp_enable"
pidfile="/var/run/mdns_afp.pid"
command="/usr/sbin/daemon"
command_args="-p ${pidfile} -f /home/matuzalem/bin/mdns_afp.sh"

load_rc_config $name
: ${mdns_afp_enable:=no}

mdns_afp_stop() {
    if [ -f "${pidfile}" ]; then
        kill `cat ${pidfile}` 2>/dev/null
        # Give the process time to exit
        sleep 1
        rm -f ${pidfile}
    fi
}

mdns_afp_status() {
    if [ -f "${pidfile}" ] && kill -0 `cat ${pidfile}` 2>/dev/null; then
        echo "mdns_afp is running (pid `cat ${pidfile}`)"
        return 0
    else
        echo "mdns_afp is not running"
        return 1
    fi
}

stop_cmd="mdns_afp_stop"
status_cmd="mdns_afp_status"

run_rc_command "$1"
