#!/bin/sh
#
# PROVIDE: mdns_ssh
# REQUIRE: mdnsd DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="mdns_ssh"
rcvar="mdns_ssh_enable"
pidfile="/var/run/mdns_ssh.pid"
command="/usr/sbin/daemon"
command_args="-p ${pidfile} -f /home/matuzalem/bin/mdns_ssh.sh"

load_rc_config $name
: ${mdns_ssh_enable:=no}

mdns_ssh_stop() {
    if [ -f "${pidfile}" ]; then
        kill `cat ${pidfile}` 2>/dev/null
        # Give the process time to exit
        sleep 1
        rm -f ${pidfile}
    fi
}

mdns_ssh_status() {
    if [ -f "${pidfile}" ] && kill -0 `cat ${pidfile}` 2>/dev/null; then
        echo "mdns_ssh is running (pid `cat ${pidfile}`)"
        return 0
    else
        echo "mdns_ssh is not running"
        return 1
    fi
}

stop_cmd="mdns_ssh_stop"
status_cmd="mdns_ssh_status"

run_rc_command "$1"
